# Site settings
title: I'm sooyoung
pageName: aaa
email: golyheart@gmail.com
description: ....
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: goldsoo
facebook_username: goldsooyoung
github_username:  goldsoo
comments: disqus_shortname _goldsoo  #disqus

# pagination
paginate: 3
paginate_path: /list/:num

# Build settings
markdown: kramdown

#separator
excerpt_separator: <!--more-->
